import {
  FaBootstrap,
  FaCss3Alt,
  FaFigma,
  FaGitAlt,
  FaGithub,
  FaHtml5,
  FaInstagram,
  FaJs,
  FaLinkedinIn,
  FaNodeJs,
  FaReact,
  FaShirt,
} from 'react-icons/fa6'
import { SiFastapi, SiJest, SiJquery, SiPrimereact, SiSitecore } from 'react-icons/si'
import {
  LuAccessibility,
  LuArrowDown,
  LuArrowRight,
  LuArrowUp,
  LuArrowUpRight,
  LuBookOpen,
  LuBot,
  LuBriefcase,
  LuCalendar,
  LuCheck,
  LuCircleAlert,
  LuCircleCheck,
  LuCloud,
  LuCopy,
  LuGauge,
  LuGraduationCap,
  LuHandshake,
  LuLoaderCircle,
  LuMail,
  LuMapPin,
  LuMessageSquareCode,
  LuMoon,
  LuMousePointer2,
  LuPause,
  LuPlay,
  LuQuote,
  LuScanSearch,
  LuSearchCheck,
  LuSend,
  LuServer,
  LuSmartphone,
  LuSparkles,
  LuSun,
  LuUsers,
  LuWorkflow,
} from 'react-icons/lu'

// Config files refer to icons by these short names.
const ICONS = {
  html: FaHtml5,
  css: FaCss3Alt,
  js: FaJs,
  react: FaReact,
  bootstrap: FaBootstrap,
  git: FaGitAlt,
  github: FaGithub,
  linkedin: FaLinkedinIn,
  instagram: FaInstagram,
  shirt: FaShirt,
  figma: FaFigma,
  node: FaNodeJs,
  fastapi: SiFastapi,
  jest: SiJest,
  jquery: SiJquery,
  primereact: SiPrimereact,
  sitecore: SiSitecore,
  bot: LuBot,
  'check-circle': LuCircleCheck,
  cloud: LuCloud,
  eval: LuScanSearch,
  handshake: LuHandshake,
  prompt: LuMessageSquareCode,
  users: LuUsers,
  workflow: LuWorkflow,
  accessibility: LuAccessibility,
  'arrow-down': LuArrowDown,
  'arrow-right': LuArrowRight,
  'arrow-up': LuArrowUp,
  'arrow-up-right': LuArrowUpRight,
  book: LuBookOpen,
  briefcase: LuBriefcase,
  calendar: LuCalendar,
  check: LuCheck,
  alert: LuCircleAlert,
  copy: LuCopy,
  gauge: LuGauge,
  graduation: LuGraduationCap,
  loader: LuLoaderCircle,
  mail: LuMail,
  pin: LuMapPin,
  moon: LuMoon,
  cursor: LuMousePointer2,
  pause: LuPause,
  play: LuPlay,
  quote: LuQuote,
  search: LuSearchCheck,
  send: LuSend,
  server: LuServer,
  mobile: LuSmartphone,
  sparkles: LuSparkles,
  sun: LuSun,
}

export default function Icon({ name, className, size = '1em' }) {
  const Cmp = ICONS[name]
  if (!Cmp) return null
  return <Cmp className={className} size={size} aria-hidden="true" focusable="false" />
}
